### ISSUE TITLE
Build Error: [partio-build/src/tests/CMakeFiles/testmerge.dir/build.make:87: testmerge] Error 1

### ISSUE THREAD

**Issue by Victorlouisdg** [ipc-sim/Codim-IPC#1]
Hi, I'm getting this vague build error that I'm not sure how to resolve. Sorry for the huge screenshot, but I'm not sure which parts are relevant:
![build_error](https://user-images.githubusercontent.com/23340946/141093947-b4a657b2-00da-4385-b7c6-8b9f83f9cbf9.png)

**Comment by Victorlouisdg** [comment]
Current workaround in `Codim-IPC/build/partio-src/CMakeLists.txt` remove these parts:

```
if (${GTEST_ENABLED})
    set($GEST_LOCATION "/usr" CACHE STRING "gtest installation prefix")
    set(GTEST_INCLUDE_PATH ${GTEST_LOCATION}/include)
    set(GTEST_LIBDIR ${CMAKE_INSTALL_LIBDIR})
    set(GTEST_LINK_PATH ${GTEST_LOCATION}/${GTEST_LIBDIR} CACHE STRING "gtest library directory")
endif()
```
```
ADD_SUBDIRECTORY (src/tests)
```
There's probably a simpler way to do this with a build flag or something, but this works for now.

**Comment by liminchen** [comment]
Hi Victor-Louis, thanks for spotting this and providing a solution! I think removing these parts is totally fine!
But I didn't encounter it in a new machine with Ubuntu 20.04. What OS are you using?

**Comment by Victorlouisdg** [comment]
I'm using Ubuntu 20.04 as well. I've been using this machine for a while, so some of the installed system packages might differ.

I'm not sure what could cause the difference, but it doesn't really matter, so I'll close this issue for now.
