### ISSUE TITLE
Help with running the simulation

### ISSUE THREAD

**Issue by AsadMah** [ipc-sim/Codim-IPC#11]
Hi I'm trying to run the simulation, I'm able to run python batch.py, but it does not open a viewer, is that expected?
can you provide more documentation on how to run it with the example projects you provided?

Thank you

**Comment by liminchen** [comment]
Yeah, there is no built-in viewer in Codim-IPC. All simulation results will
be output as obj files, which can be visualized using any renderer.
To see how to setup scenes, the python script executed by the batch.py can
be good examples.

Best,
Minchen
