### ISSUE TITLE
cannot download mkl-include and mkl-static

### ISSUE THREAD

**Issue by zhengyuf** [ipc-sim/Codim-IPC#18]
Hello,

Thanks for the great work. It seems, that the mkl-include and mkl-static packages are no longer available at the old urls. Could you update or let me know how to fix this? Thank you very much!

`error: downloading 'https://anaconda.org/intel/mkl-include/2021.3.0/download/linux-64/mkl-include-2021.3.0-intel_520.tar.bz2' failed
          status_code: 22
          status_string: "HTTP response code said error"
`

**Comment by liminchen** [comment]
Yeah, it seems that there are some updates in anaconda. Switching the anaconda url in `CMake/mkl.cmake` to
`https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/intel/${MKL_PLATFORM}/${${name}-${MKL_PLATFORM}-file}`
may help.

**Comment by zhengyuf** [comment]
Yes that fixed it. Thank you very much! :)
