### ISSUE TITLE
Rod bending question

### ISSUE THREAD

**Issue by sdast9** [ipc-sim/Codim-IPC#2]
First, thank you for making this incredible work available publicly. In playing with this a bit to see if it might be useful for a specific application related to our research, it appears that the code assumes that the initial configuration of any rod is straight. For example, if a rod with a curved geometry is imported, a bending stiffness multiplier greater than zero will cause the rod to want to assume a straight orientation. Thus, for an example of a curled hair, there doesn't appear to be a way to define its curled reference configuration as a zero stress state. In other words, you could not deform that hair with a non-zero bending stiffness, release that boundary condition, and then have the hair return to its curled state. It would be wonderful if you could let me know if this a limitation of the current version of this code or am I missing something? Again, thanks for your outstanding contributions to the field.

**Comment by liminchen** [comment]
Yes, the rod bending energy used in this codebase only supports a straight rest shape. In addition, we didn't include rod twisting energy for rods in this code. To support curve rest shape, both a more general bending model and a twisting model are needed.

**Comment by sdast9** [comment]
Thanks so much for the quick response. Are there any plans to add those at this time? Just curious.

**Comment by liminchen** [comment]
Currently, we don't have such a plan. But anyone is welcome to implement and submit pull requests if interested.
