### ISSUE TITLE
how to visualize simulation process?

### ISSUE THREAD

**Issue by ZeyingXuHuaWei** [ipc-sim/Codim-IPC#3]
Dear author, thank you for opensourcing your excellent work. 
How can I visualize the simulation? I see initialize_gui() function in SimulationBase.py. But I am not clear how to show gui. Thank you very much

**Comment by liminchen** [comment]
In this work we didn't write our own visualizer. But all geometries are
output to files which can be visualized with any rendering software.

Minchen
