### ISSUE TITLE
Meaning of muComp

### ISSUE THREAD

**Issue by Victorlouisdg** [ipc-sim/Codim-IPC#4]
I was wondering about the meaning of `muComp` variable. If I understand correctly, `mu` is used as the coefficient of friction between all objects in the simulation. I don't yet understand what happens when both `mu` and `muComp` are set.

For example `6_cloth_on_rotating_sphere.py` `mu` and `muComp` are set like so:
```python
sim.mu = 0.4
sim.muComp = StdVectorXd([0, 0, sim.mu,  0, 0, sim.mu,  sim.mu, sim.mu, 0.1])
```
What does the `muComp` vector mean here and how can we use it?

**Comment by liminchen** [comment]
When muComp is set, mu will be overwritten. muComp explicitly set different friction coefficient between each pair of bodies indexed by the order you add them to the simulator.

**Comment by Victorlouisdg** [comment]
Thanks!
