### ISSUE TITLE
Run paper examples on GPU

### ISSUE THREAD

**Issue by gdangalov** [ipc-sim/Codim-IPC#5]
Hello! I'd like to say that what you've accomplish is amazing and this work looks very promising!
Is there a way to run the examples simulation on GPU (cuda)? I use ubuntu and have Nvidia card. Is CPU the only way? Is there a way to speed up things a little bit?

**Comment by liminchen** [comment]
Hello! Thank you! This code can only run on the CPU. A GPU implementation might help improve the efficiency.
